### ISSUE TITLE
Not keeping seed for reproducability

### ISSUE THREAD

**Issue by jordanseider** [biomodhub/biomod2#54] opened 2022-04-04 18:24 UTC
Repeat runs of the same model with same `set.seed(123)` line result in different model outputs and non-reproducibility.
In particular, I am using the GLM, GBM, ANN, MARS, and RF models.

**Comment by MayaGueguen** [comment] 2022-04-08 12:24
Hi Jordan,

Yes, there is actually some `set.seed()` directly coded into the `biomod2` code...
Especially for the `GBM`, `CTA`, `ANN` and `RF` models. Which is why you are certainly not getting your reproductible results, sorry .
I'll try to add in the coming days an optional parameter within the `BIOMOD_Modeling` function, to allow the user to give a predefined seed, if you think that could be a nice option :)

Sorry for the disagreement.

Maya

**Comment by MayaGueguen** [comment] 2022-04-27 11:44
Hi Jordan,

I just committed a new version adding a `seed.val` parameter within the `BIOMOD_Modeling` function.
It would be very kind of you if you could test it and tell me back if it seems to work for you 🙏 :)

Thanks in advance
Maya

**Comment by jordanseider** [comment] 2022-04-27 19:27
Hi Maya, 

Thanks for implementing this parameter! Looks good on my end and will help a lot. 

Much appreciated,
Jordan

**Comment by jordanseider** [comment] 2022-04-27 19:44
Hi Maya, 

Thanks for working on this implementation. 

For some reason, prior to installing the newest devel update, I was able to use the `seed.val` parameter with success. This is odd though as I'm sure I had a version prior to this new version (and the `?BIOMOD_Modeling` help page did not mention `seed.val`).

After installing this new devel version, I get an error when running the `BIOMOD_Modeling` step. If I do not set the `seed.val` parameter, I get this error:

```
> # Model single models
> myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
+                                     bm.options = myBiomodOptions,
+                                     modeling.id = 'AllModels',
+                                     nb.rep = 1,
+                                     data.split.perc = 80,
+                                     # data.split.table = myBiomodCV,
+                                     var.import = 0,
+                                     metric.eval = c('TSS','ROC'),
+                                     do.full.models = FALSE)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...
Warning in .BIOMOD_Modeling.check.args(bm.format, models, bm.options, nb.rep,  :
  MAXENT.Phillips has been disabled because the maxent.jar file is missing. `maxent.jar` file must be downloaded (https://biodiversityinformatics.amnh.org/open_source/maxent/) and put in the working directory.

Creating suitable Workdir...

	> Automatic weights creation to rise a 0.5 prevalence


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GuloGulo Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 5  environmental variables ( bio3 bio4 bio7 bio11 bio12 )
Number of evaluation repetitions : 1
Models selected : GLM GBM GAM CTA ANN SRE FDA MARS RF MAXENT.Phillips.2 

Total number of model runs: 10 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


-=-=-=- Run :  GuloGulo_AllData 


-=-=-=--=-=-=- GuloGulo_AllData_RUN1 

Model=GLM ( quadratic with no interaction )
	Stepwise procedure using AIC criteria
Model=Generalised Boosting Regression 
	 2500 maximum different trees and  3  Fold Cross-Validation
Model=GAM
	 GAM_mgcv algorithm chosen
Model=Classification tree 
	 5 Fold Cross-Validation
Model=Artificial Neural Network 
	 5 Fold Cross Validation + 3 Repetitions
Model=Surface Range Envelop
Model=Flexible Discriminant Analysis
Model=Multiple Adaptive Regression Splines ( simple with no interaction )

Model=Breiman and Cutler's random forests for classification and regression
Model=MAXENT.Phillips (maxnet)Error in { : task 1 failed - "object 'seedval' not found"
In addition: Warning message:
executing %dopar% sequentially: no parallel backend registered 
> # nb.cpu = 8)
```

If I **do** include a `seed.val` parameter, I get a slightly different error...

```
> # Model single models
> myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
+                                     bm.options = myBiomodOptions,
+                                     modeling.id = 'AllModels',
+                                     nb.rep = 1,
+                                     data.split.perc = 80,
+                                     # data.split.table = myBiomodCV,
+                                     var.import = 0,
+                                     metric.eval = c('TSS','ROC'),
+                                     do.full.models = FALSE,
+                                     seed.val = 123)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...
Warning in .BIOMOD_Modeling.check.args(bm.format, models, bm.options, nb.rep,  :
  MAXENT.Phillips has been disabled because the maxent.jar file is missing. `maxent.jar` file must be downloaded (https://biodiversityinformatics.amnh.org/open_source/maxent/) and put in the working directory.

Creating suitable Workdir...

	> Automatic weights creation to rise a 0.5 prevalence


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GuloGulo Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 5  environmental variables ( bio3 bio4 bio7 bio11 bio12 )
Number of evaluation repetitions : 1
Models selected : GLM GBM GAM CTA ANN SRE FDA MARS RF MAXENT.Phillips.2 

Total number of model runs: 10 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


-=-=-=- Run :  GuloGulo_AllData 


-=-=-=--=-=-=- GuloGulo_AllData_RUN1 

Model=GLM ( quadratic with no interaction )
	Stepwise procedure using AIC criteria
Model=Generalised Boosting Regression 
	 2500 maximum different trees and  3  Fold Cross-Validation
Model=GAM
	 GAM_mgcv algorithm chosen
Model=Classification tree 
	 5 Fold Cross-Validation
Model=Artificial Neural Network 
	 5 Fold Cross Validation + 3 Repetitions
Model=Surface Range Envelop
Model=Flexible Discriminant Analysis
Model=Multiple Adaptive Regression Splines ( simple with no interaction )

Model=Breiman and Cutler's random forests for classification and regression
Model=MAXENT.Phillips (maxnet)Error in { : task 1 failed - "object 'seedval' not found"
> # nb.cpu = 8)
```

Even if I try run the model without the MAXENT algorithm (keeping everything else the same), I get an error...

```
Checking Models arguments...
Warning in .BIOMOD_Modeling.check.args(bm.format, models, bm.options, nb.rep,  :
  MAXENT.Phillips has been disabled because the maxent.jar file is missing. `maxent.jar` file must be downloaded (https://biodiversityinformatics.amnh.org/open_source/maxent/) and put in the working directory.

Creating suitable Workdir...
Error in dir.create(file.path(sp.name, ".BIOMOD_DATA", modeling.id), showWarnings = FALSE,  : 
  invalid 'path' argument
> # nb.cpu = 8)
```

**Comment by MayaGueguen** [comment] 2022-04-28 08:11
Many thanks Jordan for your feedbacks !
I'll check right away the problem with MAXENT, I think I see what's going there, and we'll see what's left then.

**Comment by MayaGueguen** [comment] 2022-04-28 08:52
I did a new update. I expect it to correct the problems with MAXENT. Would be nice if you could check again :)
I'm more sceptical about this error `Creating suitable workdir`...
Please tell me if you still have it.

**Comment by jordanseider** [comment] 2022-04-28 17:03
Hi Maya, still getting the same errors. Below is the code I've used to run and the error messages. I've been using the example code on the biomod2 website, not my own. I guess since the Maxent issue is just a warning, it's not the problem stopping the run but this `Creating suitable Workdir...` is an actual error.

```
library(biomod2)
library(raster)

# Load species occurrences (6 species available)
myFile <- system.file('external/species/mammals_table.csv', package = 'biomod2')
DataSpecies <- read.csv(myFile, row.names = 1)
head(DataSpecies)

# Select the name of the studied species
myRespName <- 'GuloGulo'

# Get corresponding presence/absence data
myResp <- as.numeric(DataSpecies[, myRespName])

# Get corresponding XY coordinates
myRespXY <- DataSpecies[, c('X_WGS84', 'Y_WGS84')]

# Load environmental variables extracted from BIOCLIM (bio_3, bio_4, bio_7, bio_11 & bio_12)
myFiles <- paste0('external/bioclim/current/bio', c(3, 4, 7), '.grd')
myExpl <- raster::stack(system.file(myFiles, package = 'biomod2'))

# Format Data with true absences
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                     expl.var = myExpl,
                                     resp.xy = myRespXY,
                                     resp.name = myRespName)

# Create default modeling options
myBiomodOptions <- BIOMOD_ModelingOptions()

# Model single models
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    bm.options = myBiomodOptions,
                                    modeling.id = c("RF", "ANN", "GLM", "MARS", "GBM"),
                                    nb.rep = 1,
                                    data.split.perc = 80,
                                    do.full.models = FALSE,
                                    seed.val = 123)
myBiomodModelOut

get_evaluations(myBiomodModelOut)
```
Error messages:
```
> myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
+                                     bm.options = myBiomodOptions,
+                                     modeling.id = c("RF", "ANN", "GLM", "MARS", "GBM"),
+                                     nb.rep = 1,
+                                     data.split.perc = 80,
+                                     do.full.models = FALSE,
+                                     seed.val = 123)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...
Warning in .BIOMOD_Modeling.check.args(bm.format, models, bm.options, nb.rep,  :
  MAXENT.Phillips has been disabled because the maxent.jar file is missing. `maxent.jar` file must be downloaded (https://biodiversityinformatics.amnh.org/open_source/maxent/) and put in the working directory.

Creating suitable Workdir...
Error in dir.create(file.path(sp.name, ".BIOMOD_DATA", modeling.id), showWarnings = FALSE,  : 
  invalid 'path' argument
```

**Comment by MayaGueguen** [comment] 2022-04-29 08:08
Ah ! Thanks for the code. The error is coming from the `modeling.id` parameter that has been mixed up with the `models` parameter. I added a supplementary check for the `modeling.id` parameter for clearer traceback.

**Comment by jordanseider** [comment] 2022-04-29 20:10
Okay, so I tried running it using the correct `models` parameter instead. I didn't look too closely at the sample code but should have noticed this! Either way, I still get an error:
```
> myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                      bm.options = myBiomodOptions,
                                      models = c("RF", "ANN", "GLM", "MARS", "GBM"),
                                      nb.rep = 1,
                                      data.split.perc = 80,
                                      do.full.models = FALSE,
                                      seed.val = 123)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...

Creating suitable Workdir...

	> Automatic weights creation to rise a 0.5 prevalence


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= GuloGulo Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 3  environmental variables ( bio3 bio4 bio7 )
Number of evaluation repetitions : 1
Models selected : RF ANN GLM MARS GBM 

Total number of model runs: 5 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


-=-=-=- Run :  GuloGulo_AllData 


-=-=-=--=-=-=- GuloGulo_AllData_RUN1 

Model=Breiman and Cutler's random forests for classification and regression
	> RF modeling...
	Evaluating Model stuff...
Model=Artificial Neural Network 
	 5 Fold Cross Validation + 3 Repetitions
	> ANN modeling...
	Model scaling...
	Evaluating Model stuff...
Model=GLM ( quadratic with no interaction )
	Stepwise procedure using AIC criteria
Model=Multiple Adaptive Regression Splines ( simple with no interaction )

Model=Generalised Boosting Regression 
	 2500 maximum different trees and  3  Fold Cross-Validation
	> GBM modeling...Loaded gbm 2.1.8
CV: 1 
CV: 2 
CV: 3 

	Evaluating Model stuff...Error in { : task 3 failed - "object 'seedval' not found"
In addition: Warning message:
executing %dopar% sequentially: no parallel backend registered 
```

**Comment by MayaGueguen** [comment] 2022-05-02 12:42
Hello Jordan,
Sorry for this, I didn't put my mind correctly in this last week...
It should be corrected now. Please tell me if you still get an error.
Maya

**Comment by jordanseider** [comment] 2022-05-02 16:49
Hi Maya, 

No worries!
Just had another look and while the model seems able to run without error now, I still do not get the same ROC and TSS between runs with the same `seed.val`.

**Comment by MayaGueguen** [comment] 2022-05-03 08:44
Hi Jordan,

Ah ! I think I got it working properly this time :v: 
I had problem at the beginning with the tree algorithms giving different TSS values, but it seems to be OK now.
Sorry for the delay, should have not get lazy testing myself, it always ends costing more time to fix details I missed...
Thank you for your patience ! :pray: 

Maya

**Comment by jordanseider** [comment] 2022-05-03 16:59
No worries! Thanks for putting in the time :) Wasn't too difficult to do these test runs, just the time difference between us! 
Looks like it's all working now! 

Jordan

**Closed** 2022-05-06 08:23 UTC
