### ISSUE TITLE
Is there an issue with running MARS?

### ISSUE THREAD

**Issue by fitzLab-AL** [biomodhub/biomod2#13] opened 2020-03-27 17:23 UTC
Both when using my own data and when running the example in the 'BIOMOD_Modeling' help documentation, MARS fails with the following error (Note I ran 'SRE' and 'MARS', see below):

**Model=Surface Range Envelop
	Evaluating Model stuff...
Model=Multiple Adaptive Regression Splines ( simple with no interaction )
Error in validObject(.Object) : 
  invalid class “MARS_biomod2_model” object: FALSE
In addition: Warning message:
glm.fit: fitted probabilities numerically 0 or 1 occurred**

I ran the exact example code in the help document, change only 'RF' to 'MARS' in the models argument, as follows:

```{r}myBiomodModelOut <- 
  BIOMOD_Modeling(
    myBiomodData,
    models = c('SRE','MARS'), #RF changed to MARS
    models.options = myBiomodOption,
    NbRunEval = 2,
    DataSplit = 80,
    VarImport = 0,
    models.eval.meth = c('TSS','ROC'),
    do.full.models = FALSE,
    modeling.id = "test"
  )
```
 
Thanks for any insights you can provide!

**Comment by TarekHattab** [comment] 2020-04-03 11:50
I have a very similar problem. The MARS model, continues to fail and produce the error, even using the example data in BIOMOD_Modeling function. 

**Model=Multiple Adaptive Regression Splines ( simple with no interaction )
Error in validObject(.Object) : 
  invalid class “MARS_biomod2_model” object: FALSE**

There is also a similar post on the r-forge page http://r-forge.r-project.org/forum/forum.php?set=custom&forum_id=4342&style=nested&max_rows=50

This bug seems to be related to the last update of 2020-02-26, my scripts were working before the update. If you have any insight on this, it would  be great.

**Comment by fitzLab-AL** [comment] 2020-04-06 12:29
Any updates / solutions for this problem?

**Comment by DamienGeorges** [comment] 2020-04-06 13:00
Hi all,

sorry for the reaction time lag..
This should be fixed in the latest version of biomod2 available on github (7b858b538d87965b5c03b46177cd9cbbfea515c7)

please update the package `devtools::install_github('biomodhub/biomod2')` and dive it a try.

Cheers,
Damien

**Closed by DamienGeorges** 2020-04-06 13:00 UTC

**Comment by grgurev** [comment] 2020-05-30 20:41
I'm reopening this as I too have the problem with this error. When using MARS, the error is same as above:
```
...
Model=Multiple Adaptive Regression Splines ( simple with no interaction )
Error in validObject(.Object) : 
  invalid class “MARS_biomod2_model” object: FALSE
```

I have the latest version from Github installed (324ba7c6). 
Any idea how to fix this?

**Comment by DamienGeorges** [comment] 2020-06-19 12:45
Any reporducible example?
