### ISSUE TITLE
maxent error

### ISSUE THREAD

**Issue by chenyongpeng1** [biomodhub/biomod2#139] opened 2022-11-22 13:08 UTC
Hello, when I used version 4.2.1 of biomod2 for modeling, I found that maxent had an error.

Model=MAXENT.Phillips
	> MAXENT.Phillips modeling...
		Creating Maxent Temp Proj Data...Error: Initialization flags not understood: 2>, ./apis/models/AllModels/apis_PA1_RUN1_MAXENT.Phillips_outputs/maxent.stderr

Model=MAXENT.Phillips (maxnet)
	> MAXENT.Phillips.2 modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  ===================================================================| 100%
Error in { : task 9 failed - "cannot open the connection"

Best，chen

**Comment by rpatin** [comment] 2022-11-23 13:12
Hello Chen,
Thank you for reporting :pray: 

Could you also share the code you used. How did you call:
-  `BIOMOD_FormatingData` 
- `BIOMOD_ModelingOptions`
- `BIOMOD_Modeling` 

Also did you have any other messages or warnings from `BIOMOD_Modeling` ?

Thanks in advance,
Best,
Rémi

**Comment by chenyongpeng1** [comment] 2022-11-24 04:27
Hello Rémi，
Fristly，I try to format Data with true absences _BIOMOD_FormatingData_. ， when plotting plot(myBiomodData)，and the graphic display is incomplete. 
![image](https://user-images.githubusercontent.com/104480028/203682452-3a352203-3747-472b-8fa6-5255554c391f.png)
```
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                    expl.var = myExpl,
                                    resp.xy = myRespXY,
                                    resp.name = myRespName)

plot(myBiomodData)

bm_DefaultModelingOptions()
myBiomodOptions <- BIOMOD_ModelingOptions()
myBiomodOptions

myBiomodCV <- BIOMOD_CrossValidation(bm.format = myBiomodData)
head(myBiomodCV)

myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    bm.options = myBiomodOptions,
                                    modeling.id = 'AllModels',
                                    models = c( "GLM", "GBM", "CTA", "ANN", "SRE", "FDA", "RF"，"MAXENT.Phillips", "MAXENT.Phillips.2"),
                                     nb.rep = 3,
                                    data.split.perc = 80,
                                    var.import = 2,
                                    metric.eval = c('TSS','ROC'),
                                    nb.cpu = 60,
                                    do.full.models = FALSE,
                                    seed.val = 123)
```

Then I ignore it and continue with the following code, errors occur in "MAXENT.Phillips", "MAXENT.Phillips.2" when modeling.



Secondly, I tried use to pseudo-absence points to model, and the result was the same error. My code is as follows：


```
myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 2,
                                       PA.nb.absences = 10000,
                                       na.rm = T,
                                       PA.strategy = 'random')

bm_DefaultModelingOptions()
myBiomodOptions <- BIOMOD_ModelingOptions()
myBiomodOptions

myBiomodCV <- BIOMOD_CrossValidation(bm.format = myBiomodData)
head(myBiomodCV)

myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    bm.options = myBiomodOptions,
                                    modeling.id = 'AllModels',
                                    models = c( "GLM", "GBM", "CTA", "ANN", "SRE", "FDA", "RF"，"MAXENT.Phillips", "MAXENT.Phillips.2"),
                                     nb.rep = 3,
                                    data.split.perc = 80,
                                    var.import = 2,
                                    metric.eval = c('TSS','ROC'),
                                    nb.cpu = 60,
                                    do.full.models = FALSE,
                                    seed.val = 123)
```
And I found that Biomod was updated again. I will try to report to you again.
Many thanks！
Cheers，chen

**Comment by chenyongpeng1** [comment] 2022-11-24 05:43
> plot(myBiomodData.r)
Error in if (min(global(x@data.mask, min)) == -1) { : 
  missing value where TRUE/FALSE needed

**Comment by rpatin** [comment] 2022-11-24 09:08
Hi Chen, 

Thank you for the update. Something may have gone wrong in your `BIOMOD_FormatingData` which may be linked to your data. I'll add a few questions:
- What is the summary of  `myBiomodData` ? (if you type `myBiomodData` into the console)
- What is the summary of  `myBiomodData.r` ? (if you type `myBiomodData.r` into the console)
- Did you have warnings/error in both calls to `BIOMOD_FormatingData` ?
- Which error did you get with `BIOMOD_Modeling` ? Can you print the full output ?

Thanks in advance,
Cheers,
Rémi

**Comment by chenyongpeng1** [comment] 2022-11-24 09:18
Hello Rémi,
    Thank you for your many helps.I type myBiomodData.r or myBiomodData into the console，it can display normally.
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data.PA -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  apis

	 11798 presences,  40 true absences and  11456 undefined points in dataset


	 12 explanatory variables

     bio_1             bio_3             bio_2            bio_8            bio_9             bio_12           bio_14      
 Min.   :-25.479   Min.   :  9.807   Min.   : 1.000   Min.   :-14.10   Min.   :-40.684   Min.   :   0.0   Min.   :  0.00  
 1st Qu.:  5.328   1st Qu.: 26.644   1st Qu.: 8.522   1st Qu.: 10.79   1st Qu.: -3.949   1st Qu.: 377.0   1st Qu.:  5.00  
 Median : 10.135   Median : 34.638   Median :11.099   Median : 16.68   Median :  5.841   Median : 633.0   Median : 19.00  
 Mean   : 10.984   Mean   : 39.245   Mean   :11.072   Mean   : 16.53   Mean   :  5.874   Mean   : 743.7   Mean   : 26.25  
 3rd Qu.: 19.683   3rd Qu.: 47.948   3rd Qu.:13.230   3rd Qu.: 22.95   3rd Qu.: 19.429   3rd Qu.: 954.0   3rd Qu.: 40.00  
 Max.   : 30.197   Max.   :100.000   Max.   :20.011   Max.   : 36.95   Max.   : 37.035   Max.   :7150.0   Max.   :476.00  
     bio_15           bio_18           bio_19          land_use          elev       
 Min.   :  0.00   Min.   :   0.0   Min.   :   0.0   Min.   : 1.00   Min.   :-137.0  
 1st Qu.: 26.66   1st Qu.: 120.0   1st Qu.:  36.0   1st Qu.: 7.00   1st Qu.: 125.0  
 Median : 44.92   Median : 201.0   Median :  97.0   Median : 9.00   Median : 298.0  
 Mean   : 52.58   Mean   : 220.6   Mean   : 144.3   Mean   : 7.91   Mean   : 562.8  
 3rd Qu.: 71.25   3rd Qu.: 284.0   3rd Qu.: 181.0   3rd Qu.:10.00   3rd Qu.: 676.0  
 Max.   :208.99   Max.   :2579.0   Max.   :3401.0   Max.   :12.00   Max.   :5977.0  


 2 Pseudo Absences dataset available ( PA1 PA2 ) with  5859 absences in each (true abs + pseudo abs)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Thanks again!
cheers,chen

**Comment by chenyongpeng1** [comment] 2022-11-24 11:58
Hello Rémi,
```
1.> plot(myBiomodData.r)
Error in if (min(global(x@data.mask, min)) == -1) { : 
  missing value where TRUE/FALSE needed
2.
Model=MAXENT.Phillips
	> MAXENT.Phillips modeling...
		Creating Maxent Temp Proj Data...Error: Initialization flags not understood: 2>, ./apis/models/AllModels/apis_PA1_RUN1_MAXENT.Phillips_outputs/maxent.stderr

Model=MAXENT.Phillips (maxnet)
	> MAXENT.Phillips.2 modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
```
  |====================================================================| 100%

Error in { : task 9 failed - "cannot open the connection"
![image](https://user-images.githubusercontent.com/104480028/203779101-fcd92bbc-cb1d-4078-ac39-6ec8eedd726f.png)

**Comment by rpatin** [comment] 2022-11-24 12:35
Hello Chen,
I am sorry my questions might not have been precise enough.
I would like to know:
1. What happens when you call:
```
myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
                                    expl.var = myExpl,
                                    resp.xy = myRespXY,
                                    resp.name = myRespName)
myBiomodData
```
Could you copy-paste everything that R is printing in the console ?

2. What happens when you call:
```
myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp,
                                       expl.var = myExpl,
                                       resp.xy = myRespXY,
                                       resp.name = myRespName,
                                       PA.nb.rep = 2,
                                       PA.nb.absences = 10000,
                                       na.rm = T,
                                       PA.strategy = 'random')
myBiomodData.r
```
Same, could you copy-paste everything that R is printing in the console

3. What happens when you call:
```
myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData,
                                    bm.options = myBiomodOptions,
                                    modeling.id = 'AllModels',
                                    models = c( "GLM", "GBM", "CTA", "ANN", "SRE", "FDA", "RF"，"MAXENT.Phillips", "MAXENT.Phillips.2"),
                                     nb.rep = 3,
                                    data.split.perc = 80,
                                    var.import = 2,
                                    metric.eval = c('TSS','ROC'),
                                    nb.cpu = 60,
                                    do.full.models = FALSE,
                                    seed.val = 123)
```
Same, could you copy-paste everything that R is printing in the console (and not only the error about `MAXENT.Phillips`, I am wondering what the model would have tell you before).

4. If you prefer I can also try to reproduce your error if you can send me your data (_myResp, myExpl, myRespXY_) by mail for instance (remi.patin@univ-grenoble-alpes.fr)

Cheers,
Rémi

**Comment by chenyongpeng1** [comment] 2022-11-24 13:24
Hello Rémi,
I have sent the data file data-1 to your mailbox, and I try to copy-paste everything that R is printing in the console.
1.  myBiomodData <- BIOMOD_FormatingData(resp.var = myResp,
+                                     expl.var = myExpl,
+                                     resp.xy = myRespXY,
+                                     resp.name = myRespName)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= apis Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

> No pseudo absences selection !
      ! No data has been set aside for modeling evaluation
			! Some NAs have been automatically removed from your data
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> myBiomodData

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  apis

	 24047 presences,  40 true absences and  0 undefined points in dataset


	 12 explanatory variables

     bio_1            bio_3           bio_2            bio_8            bio_9              bio_12           bio_14      
 Min.   :-8.875   Min.   :15.61   Min.   : 3.775   Min.   :-9.208   Min.   :-24.4785   Min.   :   0.0   Min.   :  0.00  
 1st Qu.: 7.868   1st Qu.:29.40   1st Qu.: 8.070   1st Qu.:10.002   1st Qu.: -0.4839   1st Qu.: 603.0   1st Qu.: 22.00  
 Median : 9.841   Median :33.72   Median :10.123   Median :16.263   Median :  5.2455   Median : 784.0   Median : 37.00  
 Mean   :11.488   Mean   :37.52   Mean   :10.402   Mean   :15.261   Mean   :  6.9676   Mean   : 839.6   Mean   : 37.77  
 3rd Qu.:15.282   3rd Qu.:41.48   3rd Qu.:12.317   3rd Qu.:20.416   3rd Qu.: 15.3540   3rd Qu.: 989.0   3rd Qu.: 51.00  
 Max.   :28.924   Max.   :92.83   Max.   :19.974   Max.   :33.722   Max.   : 37.0353   Max.   :5575.0   Max.   :341.00  
     bio_15           bio_18           bio_19          land_use           elev       
 Min.   :  0.00   Min.   :   0.0   Min.   :   0.0   Min.   : 1.000   Min.   :-137.0  
 1st Qu.: 18.56   1st Qu.: 174.0   1st Qu.: 105.0   1st Qu.: 7.000   1st Qu.:  90.0  
 Median : 29.16   Median : 218.0   Median : 159.0   Median : 9.000   Median : 235.0  
 Mean   : 36.00   Mean   : 237.6   Mean   : 179.8   Mean   : 8.073   Mean   : 434.4  
 3rd Qu.: 46.59   3rd Qu.: 290.0   3rd Qu.: 209.0   3rd Qu.:10.000   3rd Qu.: 468.0  
 Max.   :150.89   Max.   :1497.0   Max.   :1520.0   Max.   :12.000   Max.   :5225.0  

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> plot(myBiomodData)

2.myBiomodData.r <- BIOMOD_FormatingData(resp.var = myResp,
+                                        expl.var = myExpl,
+                                        resp.xy = myRespXY,
+                                        resp.name = myRespName,
+                                        PA.nb.rep = 2,
+                                        PA.nb.absences = 10000,
+                                        na.rm = T,
+                                        PA.strategy = 'random')

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= apis Data Formating -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

      ! No data has been set aside for modeling evaluation

Checking Pseudo-absence selection arguments...

   > random pseudo absences selection
   > Pseudo absences are selected in explanatory variables
			! Some NAs have been automatically removed from your data
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Done -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
> 
> 
> 
> 
> plot(myBiomodData.r)
Error in if (min(global(x@data.mask, min)) == -1) { : 
  missing value where TRUE/FALSE needed

3. myBiomodModelOut <- BIOMOD_Modeling(bm.format = myBiomodData.r,
+                                     bm.options = myBiomodOptions,
+                                     modeling.id = 'AllModels',
+                                     models = c( "GLM", "GBM", "GAM", "CTA", "ANN", "SRE", "FDA",  "RF","MAXENT.Phillips", "MAXENT.Phillips.2"),
+                                      nb.rep = 2,
+                                     data.split.perc = 80,
+                                     # data.split.table = myBiomodCV,
+                                     var.import = 2,
+                                     metric.eval = c('TSS','ROC'),
+                                     nb.cpu =60 ,
+                                     do.full.models = FALSE,
+                                     seed.val = 123)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= Build Single Models -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


Checking Models arguments...

Creating suitable Workdir...

			! Weights where automatically defined for apis_PA1 to rise a 0.5 prevalence !
			! Weights where automatically defined for apis_PA2 to rise a 0.5 prevalence !


-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= apis Modeling Summary -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 12  environmental variables ( bio_1 bio_3 bio_2 bio_8 bio_9 bio_12 bio_14 bio_15 bio_18 bio_19 land_use elev )
Number of evaluation repetitions : 2
Models selected : GLM GBM GAM CTA ANN SRE FDA RF MAXENT.Phillips MAXENT.Phillips.2 

Total number of model runs: 40 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=


-=-=-=- Run :  apis_PA1 


-=-=-=--=-=-=- apis_PA1_RUN1 

Model=GLM ( quadratic with no interaction )
	Stepwise procedure using AIC criteria
	> GLM modeling...
	Automatic formula generation...
	selected formula : apis ~ bio_9 + bio_15 + I(bio_1^2) + bio_1 + bio_2 + bio_19 + 
    I(bio_19^2) + I(bio_12^2) + bio_12 + I(bio_2^2) + elev + 
    I(elev^2) + bio_14 + I(bio_14^2) + I(bio_15^2) + bio_18 + 
    I(land_use^2) + I(bio_3^2) + bio_3

	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |===========================================================================================================================| 100%


Model=Generalised Boosting Regression 
	 2500 maximum different trees and  3  Fold Cross-Validation
	> GBM modeling...CV: 1 
CV: 2 
CV: 3 

	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |===========================================================================================================================| 100%


Model=GAM
	 GAM_mgcv algorithm chosen
	Automatic formula generation...
	> GAM (mgcv) modeling...
*** single value predicted
   ! Note :  apis_PA1_RUN1_GAM failed!

Model=Classification tree 
	 5 Fold Cross-Validation
	> CTA modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |===========================================================================================================================| 100%


Model=Artificial Neural Network 
	 5 Fold Cross Validation + 3 Repetitions
	> ANN modeling...
	Model scaling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |===========================================================================================================================| 100%


Model=Surface Range Envelop
	> SRE modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |===========================================================================================================================| 100%


Model=Flexible Discriminant Analysis
	> FDA modeling...
	Model scaling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |===========================================================================================================================| 100%


Model=Breiman and Cutler's random forests for classification and regression
	> RF modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |===========================================================================================================================| 100%


Model=MAXENT.Phillips
	> MAXENT.Phillips modeling...
		Creating Maxent Temp Proj Data...Error: Initialization flags not understood: 2>, ./apis/models/AllModels/apis_PA1_RUN1_MAXENT.Phillips_outputs/maxent.stderr

Model=MAXENT.Phillips (maxnet)
	> MAXENT.Phillips.2 modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |===========================================================================================================================| 100%

Error in { : task 9 failed - "cannot open the connection"

Cheers,
chen

**Comment by rpatin** [comment] 2022-11-24 15:27
Great, thank your very much Chen, this is much easier to understand what was happening !
A few answers to your question:
1. Concerning the graphic you showed at the beginning I have something slightly different, but maybe you already solved that problem inbetween:
![image](https://user-images.githubusercontent.com/8982316/203817518-c1f880be-d33d-448a-83cd-92a019b2d5b0.png)
The graph looks fine for me. At least concerning the role of `biomod2`. But you can notice that there are very few absences, which you can also see in the data summary:
```
> myBiomodData

-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  apis

	 24047 presences,  40 true absences and  0 
undefined points in dataset


	 12 explanatory variables

     bio_1            bio_3           bio_2       
 Min.   :-8.875   Min.   :15.61   Min.   : 3.775  
 1st Qu.: 7.868   1st Qu.:29.40   1st Qu.: 8.070  
 Median : 9.841   Median :33.72   Median :10.123  
 Mean   :11.488   Mean   :37.52   Mean   :10.402  
 3rd Qu.:15.282   3rd Qu.:41.48   3rd Qu.:12.317  
 Max.   :28.924   Max.   :92.83   Max.   :19.974  
     bio_8            bio_9              bio_12      
 Min.   :-9.208   Min.   :-24.4785   Min.   :   0.0  
 1st Qu.:10.002   1st Qu.: -0.4839   1st Qu.: 603.0  
 Median :16.263   Median :  5.2455   Median : 784.0  
 Mean   :15.261   Mean   :  6.9676   Mean   : 839.6  
 3rd Qu.:20.416   3rd Qu.: 15.3540   3rd Qu.: 989.0  
 Max.   :33.722   Max.   : 37.0353   Max.   :5575.0  
     bio_14           bio_15           bio_18      
 Min.   :  0.00   Min.   :  0.00   Min.   :   0.0  
 1st Qu.: 22.00   1st Qu.: 18.56   1st Qu.: 174.0  
 Median : 37.00   Median : 29.16   Median : 218.0  
 Mean   : 37.77   Mean   : 36.00   Mean   : 237.6  
 3rd Qu.: 51.00   3rd Qu.: 46.59   3rd Qu.: 290.0  
 Max.   :341.00   Max.   :150.89   Max.   :1497.0  
     bio_19          land_use           elev       
 Min.   :   0.0   Min.   : 1.000   Min.   :-137.0  
 1st Qu.: 105.0   1st Qu.: 7.000   1st Qu.:  90.0  
 Median : 159.0   Median : 9.000   Median : 235.0  
 Mean   : 179.8   Mean   : 8.073   Mean   : 434.4  
 3rd Qu.: 209.0   3rd Qu.:10.000   3rd Qu.: 468.0  
 Max.   :1520.0   Max.   :12.000   Max.   :5225.0  

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

Also note that some of your data looks strongly aligned, which is suspicious.

2. Concerning the plot error:
```
> plot(myBiomodData.r)
    Error in if (min(global([x@data.mask](mailto:x@data.mask), min)) == -1) { :
    missing value where TRUE/FALSE needed
```
Thank you for the feedback, there is indeed an error in the plot method for data with pseudo-absences. I just pushed a commit and it should now be fixed

3. Concerning your error with `MAXENT.Phillips`:
```
 Creating Maxent Temp Proj Data...Error: Initialization flags not understood: 2>, ./apis/models/AllModels/apis_PA1_RUN1_MAXENT.Phillips_outputs/maxent.stderr
```
I could not reproduce the error so I do not know what could have happened. Did you have a look at `maxent.stderr` ?

4. Concerning the fact that your model seems to have crashed with this message:
``` 
Error in { : task 9 failed - "cannot open the connection"
```
I also could not reproduce that one so I do not know what could be happening. You are asking for 60 cores and I do not know how much RAM is available on the server you were using, maybe your process got killed ?

I Hope this helps and feel free to ask if something is unclear or to add additional informations.
Cheers,
Rémi

**Comment by chenyongpeng1** [comment] 2022-11-25 00:38
hello Rémi,
Thank you for your help and  time!
1.Concerning the plot error: it was solved.
2.There are indeed some warning messages  in  the maxent modeling  when I changed _nb.cpu = 60,_to _nb.cpu = 8._
`Model=MAXENT.Phillips
	> MAXENT.Phillips modeling...
		Creating Maxent Temp Proj Data...Error: Initialization flags not understood: 2>, ./apis/models/AllModels/apis_PA1_RUN1_MAXENT.Phillips_outputs/maxent.stderr

Model=MAXENT.Phillips (maxnet)
	> MAXENT.Phillips.2 modeling...
	Evaluating Model stuff...
	Evaluating Predictor Contributions...
  |=============================================| 100%

Error in { : task 9 failed - "cannot open the connection"
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  Parallelisation with `foreach` is not available for Windows. Sorry.
2: executing %dopar% sequentially: no parallel backend registered 
3: In newton(lsp = lsp, X = G$X, y = G$y, Eb = G$Eb, UrS = G$UrS, L = G$L,  :
  Fitting terminated with step failure - check results carefully
4: In file(con, "r") :
  cannot open file './apis/models/AllModels/apis_PA1_RUN1_MAXENT.Phillips_outputs/maxent.stderr': No such file or directory`

**Comment by chenyongpeng1** [comment] 2022-11-28 08:40
Hello Rémi,
   I try to use the 3.5.1 version of biomod2. The maxent model works well, but errors will be reported in both 4.1 and 4.2 versions.
   Best，chen

**Comment by rpatin** [comment] 2022-11-28 11:02
Hello Chen,
We finally got an idea of what could be causing the error and we suspect a bug linked to Windows not being compatible with the current call to Maxent. I pushed a commit to try and correct that but we could not test it on Windows right now so I do not know if it works.
If you update to current `biomod2` github version (4.2-1) it should hopefully be fixed now:
`devtools::install_github('biomodhub/biomod2')`
Please let us know whether that is the case or not.
Best,
Rémi

**Comment by chenyongpeng1** [comment] 2022-11-29 12:06
Hello Rémi,
 
   Thank you for your help！It has fixed well.

Cheers，Chen

**Closed** 2022-11-29 12:13 UTC
Labels: bug
