### ISSUE TITLE
Help with BIOMOD_modeling- [why Maxent failed during runing?]

### ISSUE THREAD

**Issue by mula-jpg** [biomodhub/biomod2#292] opened 2023-06-30 13:16 UTC
Hellow everyone, I am strange for the new version of Biomod2. please help me for the following issue.
 Code Used:
```
My_model<-BIOMOD_FormatingData(
  resp.name= 'myRespName',
  resp.var=myResp,
  expl.var =bioclim_curr,
  dir.name = "Vannn",
  resp.xy = myRespXY,
  eval.resp.var = NULL,
  eval.expl.var = NULL,
  eval.resp.xy = NULL,
  PA.nb.rep = 3,
  PA.nb.absences = 1000,
  PA.strategy = "random",
  PA.dist.min = 0,
  PA.dist.max = NULL,
  PA.sre.quant = 0.025,
  PA.user.table = NULL,
  na.rm = TRUE,
  filter.raster = FALSE)
##Out put of My_model
show(My_model)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name = Vannn

sp.name = myRespName

 128 presences,  0 true absences and  10000 undefined points in dataset


 9 explanatory variables

  bio3            bio4             bio7            bio9            bio13      

Min. :37.30 Min. : 45.08 Min. :13.60 Min. : 4.883 Min. : 20.0
1st Qu.:69.78 1st Qu.: 88.82 1st Qu.:16.90 1st Qu.:19.133 1st Qu.:101.0
Median :73.88 Median :114.07 Median :18.10 Median :22.100 Median :158.0
Mean :72.21 Mean :134.12 Mean :18.39 Mean :21.870 Mean :171.8
3rd Qu.:76.33 3rd Qu.:156.48 3rd Qu.:19.80 3rd Qu.:25.183 3rd Qu.:230.0
Max. :84.37 Max. :385.57 Max. :24.50 Max. :32.567 Max. :460.0
bio14 bio15 bio18 bio19
Min. : 0.000 Min. : 35.01 Min. : 17.0 Min. : 0.0
1st Qu.: 2.000 1st Qu.: 69.08 1st Qu.:113.0 1st Qu.: 32.0
Median : 5.000 Median : 89.04 Median :162.0 Median : 55.0
Mean : 8.922 Mean : 89.96 Mean :174.3 Mean : 244.9
3rd Qu.:12.000 3rd Qu.:114.43 3rd Qu.:217.0 3rd Qu.: 494.0
Max. :58.000 Max. :139.11 Max. :585.0 Max. :1156.0

1 Pseudo Absences dataset available ( PA1 ) with 10000 (PA1) pseudo absences
 ###  Modeling options        
  Mymodeling_Opt<-BIOMOD_ModelingOptions(
  GLM = list(type = 'quadratic',
             interaction.level = 0,
             myFormula = NULL,
             test = 'AIC',
             family = binomial(link = 'logit'),
             mustart = 0.5,
             control = glm.control(epsilon = 1e-08, maxit = 50, trace = FALSE)),
  GBM = list(distribution = 'bernoulli',
             n.trees = 2500,
             interaction.depth = 7,
             n.minobsinnode = 5,
             shrinkage = 0.001,
             bag.fraction = 0.5,
             train.fraction = 1,
             cv.folds = 3,
             keep.data = FALSE,
             verbose = FALSE,
             perf.method = 'cv',
             n.cores = 1),
  GAM = list(algo = 'GAM_gam',
             type = 's_smoother',
             k = -1,
             interaction.level = 0,
             myFormula = NULL,
             family = binomial(link = 'logit'),
             method = 'GCV.Cp',
             optimizer = c('outer','newton'),
             select = FALSE,
             knots = NULL,
             paraPen = NULL,
             control = list(nthreads = 1, irls.reg = 0, epsilon = 1e-07, maxit = 200,          trace = FALSE, mgcv.tol = 1e-07, mgcv.half = 15, rank.tol = 1.49011611938477e-08, nlm = list(ndigit=7, gradtol=1e-06, stepmax=2, steptol=1e-04,        iterlim=200, check.analyticals=0), optim = list(factr=1e+07), newton = list(conv.tol=1e-06, maxNstep=5, maxSstep=2, maxHalf=30, use.svd=0),           outerPIsteps = 0, idLinksBases = TRUE, scalePenalty = TRUE, efs.lspmax = 15, efs.tol = 0.1, keepData = FALSE, scale.est = NULL, edge.correct = FALSE)),
  CTA = list( method = 'class',
              parms = 'default',
              cost = NULL,
              control = list(xval = 5, minbucket = 5, minsplit = 5, cp = 0.001, maxdepth       = 25)),
  ANN = list(NbCV = 5,
             size = NULL,
             decay = NULL,
             rang = 0.1,
             maxit = 200),
  SRE = list( quant = 0.025),
  FDA = list( method = 'mars',
              add_args = NULL),
  MARS = list( type = 'simple',
               interaction.level = 0,
               myFormula = NULL,
               nk = NULL,
               penalty = 2,
               thresh = 0.001,
               nprune = NULL,
               pmethod = 'backward'),
  
  RF = list( do.classif = TRUE,
             ntree = 500,
             mtry = 'default',
             nodesize = 5,
             maxnodes = NULL),
  
  MAXENT= list( path_to_maxent.jar = 'C:/Users/DMU/Desktop/R _software/LapwingSDM',
                memory_allocated = 1024,
                background_data_dir = 'default',
                maximumbackground = 'default',
                maximumiterations = 5000,
                visible = FALSE,
                linear = TRUE,
                quadratic = TRUE,
                product = TRUE,
                threshold = TRUE,
                hinge = TRUE,
                lq2lqptthreshold = 70,
                l2lqthreshold = 10,
                hingethreshold = 15,
                beta_threshold = -1,
                beta_categorical = -1,
                beta_lqp = -1,
                beta_hinge = -1,
                betamultiplier = 1,
                defaultprevalence = 0.5))
## Biomod_modeling
Mymodel<-BIOMOD_Modeling(
  bm.format=My_model,
  modeling.id = "allmdel1",
  models = c("GLM", "GBM", "GAM", "CTA", "ANN", "SRE", "FDA", "MARS", "RF", "MAXENT"),
  models.pa = NULL,
  bm.options = Mymodeling_Opt,
  CV.strategy = "random",
  CV.nb.rep = 2,
  CV.perc = 0.7,
  CV.k = NULL,
  CV.balance = NULL,
  CV.env.var = NULL,
  CV.strat = NULL,
  CV.user.table = NULL,
  CV.do.full.models = TRUE,
  weights = NULL,
  prevalence = NULL,
  metric.eval = c("KAPPA", "TSS", "ROC"),
  var.import = 3,
  scale.models = FALSE,
  nb.cpu = 1,
  seed.val = NULL,
  do.progress = TRUE)
```
All algorithms are Ok but the maxent is failed by saying like this:

```
  model=MAXENT
	> MAXENT modeling...
		Creating Maxent Temp Proj Data...
*** Error in MAXENT, more info available in Vannn/myRespName/models/allmdel1/myRespName_PA1_RUN1_MAXENT_outputs/maxent.stderr
*** inherits(g.pred,'try-error')
   ! Note :  myRespName_PA1_RUN1_MAXENT failed!

When open the file Vannn/myRespName/models/allmdel1/myRespName_PA1_RUN1_MAXENT_outputs/maxent.stderr by NotePad, it says: Error: Unable to access jarfile C:/Users/DMU/Desktop/R.
```
What will be the reason ??

**Comment by rpatin** [comment] 2023-07-10 09:27
Hi @mula-jpg,
This seems to be a duplicate of https://github.com/biomodhub/biomod2/issues/291.
I'll close the issue and update the other one unless there is something more specific to this post.
Best,
Rémi

**Closed by rpatin** 2023-07-10 09:27 UTC
Labels: help wanted
