### ISSUE TITLE
unrecognized error message--get_predictions

### ISSUE THREAD

**Issue by tobioke** [biomodhub/biomod2#148] opened 2022-12-14 07:45 UTC
Hi there, 

I'm encountering a problem that wasn't present in my codes prior to updating to the latest version of biomod2.  It seems the error has to do with the object required for the "get_projection" function but I have examined the code thoroughly and the function was not used explicitly.  So, it seems like a bug. I was wondering if you are familiar with this error message. 

Here's the error message : 

 > Projecting Species_PA1_RUN1_GLM ...
	> Projecting Species_PA1_RUN1_GAM ...
	> Projecting Species_PA1_RUN1_RF ...
	> Projecting Species_PA1_RUN1_GBM ...
	> Projecting Species_PA1_RUN2_GLM ...
	> Projecting Species_PA1_RUN2_GAM ...
	> Projecting Species_PA1_RUN2_RF ...
	> Projecting Species_PA1_RUN2_GBM ...Error in { : 
  task 1 failed - "error in evaluating the argument 'obj' in selecting a method for function 'get_predictions': task 1 failed - "Argument eta must be a nonempty numeric vector""

It occurred in this step:

myBiomodEM <- BIOMOD_EnsembleModeling(
    bm.mod = myBiomodModelOut,
    models.chosen = 'all', 
    em.by='all',
    metric.select = c('TSS', 'ROC'),
    metric.select.thresh = c(0.5, 0.7),
    metric.eval = c('TSS', 'ROC'),
    prob.mean = TRUE,
    prob.cv = TRUE,
    prob.ci = FALSE,
    prob.ci.alpha = 0.05,
    prob.median = TRUE,
    committee.averaging = TRUE,
    prob.mean.weight = TRUE,
    prob.mean.weight.decay = 'proportional',
    var.import = 3)

**Comment by rpatin** [comment] 2022-12-14 08:55
Hi @tobioke,
Thank you for reporting and sorry for the inconvenience :pray: 

`get_predictions` is a tool function used to extract predictions from `biomod2` object and is here used internally to extract the predictions from individual models that will be used to build the ensemble models.

I think I have already seen this error but cannot remember when or what was causing it (it might have already been fixed in the newer versions). Could you provide a bit more information:
- which version of `biomod2` are you using ?  You can get it with `packageVersion("biomod2")`
- Can you send a summary of your data object (likely `show(myBiomodData)`) and your output of `BIOMOD_Modeling` (`show(myBiomodModelOut`) ? Maybe I will be able to spot the cause of the bug with that.

Thanks in advance,
Rémi

**Comment by tobioke** [comment] 2022-12-14 14:51
Hi Rémi,

Thanks for getting back to me. 

The package version is  ‘4.1.2’

See below the summary of myBiomodData and BIOMOD_Modeling

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.formated.data.PA -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

dir.name =  .

sp.name =  Species

	 1405 presences,  0 true absences and  4348 undefined points in dataset


	 9 explanatory variables

     bio17             bio9             elev             gst               hli           organic_15        sand_15          slope        
 Min.   :  8.00   Min.   :-29.07   Min.   :   1.0   Min.   :-13.575   Min.   :0.1430   Min.   :   0.0   Min.   :  0.0   Min.   : 0.0000  
 1st Qu.: 29.00   1st Qu.:-17.20   1st Qu.: 615.0   1st Qu.:  7.150   1st Qu.:0.4357   1st Qu.: 507.5   1st Qu.:271.9   1st Qu.: 0.8946  
 Median : 37.00   Median :-13.62   Median : 896.0   Median :  8.700   Median :0.4536   Median : 735.8   Median :358.1   Median : 2.3932  
 Mean   : 43.76   Mean   :-14.47   Mean   : 940.1   Mean   :  8.345   Mean   :0.4578   Mean   : 729.7   Mean   :342.3   Mean   : 3.3149  
 3rd Qu.: 50.00   3rd Qu.:-11.38   3rd Qu.:1212.0   3rd Qu.:  9.875   3rd Qu.:0.4785   3rd Qu.: 927.0   3rd Qu.:414.3   3rd Qu.: 4.7615  
 Max.   :309.00   Max.   :  5.30   Max.   :5085.0   Max.   : 13.475   Max.   :0.7548   Max.   :2062.0   Max.   :667.4   Max.   :35.1515  
      tpi          
 Min.   :-791.493  
 1st Qu.: -99.942  
 Median : -11.661  
 Mean   :   1.866  
 3rd Qu.:  93.153  
 Max.   :1966.543  


 1 Pseudo Absences dataset available ( PA1 ) with  4348 absences in each (true abs + pseudo abs)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=



-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= BIOMOD.models.out -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

Modeling folder : .

Species modeled : Species

Modeling id : SpeciesBIOMOD

Considered variables : bio17 bio9 elev gst hli organic_15 sand_15 slope tpi


Computed Models :  Species_PA1_RUN1_GLM Species_PA1_RUN1_GAM Species_PA1_RUN1_RF Species_PA1_RUN1_GBM Species_PA1_RUN2_GLM 
Species_PA1_RUN2_GAM Species_PA1_RUN2_RF Species_PA1_RUN2_GBM


Failed Models :  none

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by rpatin** [comment] 2022-12-14 15:50
Hi @tobioke,
Thank you for the additional information.
I suppose there is an issue with the merging of the PA dataset that requires additional predictions that fail for some reasons. But I fail in spotting exactly what is causing this.
I can however try to have a deeper look if you can send me your data (remi.patin@univ-grenoble-alpes.fr).
Best,
Rémi

**Comment by tobioke** [comment] 2022-12-14 16:43
Hi Rémi,

I have sent my data to your e-mail. Let me know if you do not receive it.
Thanks for your help.

Tobi

**Comment by rpatin** [comment] 2022-12-15 09:44
Hi Tobi,
Thank you for the data. This helped me a lot to reproduce and identify the error.
There was a bug in the CRAN version (_4.1-2_ that your are using) when asking for a single pseudo-absence dataset but using `em.by = 'all'`, sorry for the inconvenience :pray:. Fortunately this has been patched since then (but not available on CRAN yet). In summary you can:
- update `biomod2` to the github version with `devtools::install_github('biomodhub/biomod2')` for which this error was fixed. Feel free to let us know if you encounter troubles using the new version.
- use a second pseudo-absence dataset in your data (with `PA.nb.rep = 2` in your call to `BIOMOD_FormatingData`). This will also allow you to keep the current CRAN version at the cost of running more models (which you may or may not want).

Best,
Rémi

**Comment by rpatin** [comment] 2022-12-16 13:41
Hi Tobi,
I got the same error when running your script for this function call:
```
### Make ensemble-models projections on current variable
myBiomodEF <- BIOMOD_EnsembleForecasting( 
  bm.proj = myBiomodProj,
  EM.output = myBiomodEM,
  binary.meth = 'TSS',
  total.consensus = TRUE,
  output.format = '.img')
```
gives this error:
```
Error in .BIOMOD_EnsembleForecasting.check.args(bm.em, bm.proj, proj.name, : 
argument "bm.em" is missing, with no default
```

but changing `EM.output` into `bm.em` as follows solved it for me:
```
myBiomodEF <- BIOMOD_EnsembleForecasting( 
  bm.proj = myBiomodProj,
  bm.em = myBiomodEM,
  binary.meth = 'TSS',
  total.consensus = TRUE,
  output.format = '.img')
```

Note that among other changes in the newer version of `biomod2`:
- argument `modeling.output` in `BIOMOD_Projection` have been changed to `bm.mod`
- argument `projection.output` in `BIOMOD_EnsembleForecasting` have been changed to `bm.proj`
- argument `total.consensus` have disappeared
In case you have a doubt about argument name that may have changed, feel free to check the function documentation to check which argument are necessary and whether they match the one you gave (you have also example in the doc and on the [website](https://biomodhub.github.io/biomod2/articles/examples_1_mainFunctions.html)).

In case you still get errors when running your script, please make sure that your run it from the beginning with the new version of `biomod2`.
And in case you still get the error after all this, I would need a bit more context on how you get the error (which successive steps you do and at which point you get the error).
Best,
Rémi

**Comment by tobioke** [comment] 2022-12-16 19:14
Hi Remi,

Thank you so much for your help. It turned out that I typed `bm.Em` instead of `bm.em` in one of the lines. Thank you also for catching those other changes. Everything now runs smoothly from start to finish.

The issue now is that the `individual_projections` folder in the directory is empty. That is, biomod did not generate individual models for both the current and the future models. These are the files that I need to run further analyses. This was not a problem in the older version as the data were generated automatically. The biomod document was not helpful for this issue and I also ran the model both as a loop and in parallel, and neither produced the data. I was wondering if you have a suggestion for obtaining these data?

Thanks,

Tobi

**Comment by rpatin** [comment] 2022-12-19 15:25
Hi Tobi,
Great news that it is now working !
If you want results as individual raster (one raster per model) in the folder `individual_projections` you need to set argument `do.stack = FALSE` in `BIOMOD_Projection` or `BIOMOD_EnsembleForecasting`. 
Otherwise, by default `do.stack = TRUE` and results are saved as a single rasterfile with one layer per model (which can also be used to extract individual model raster).
Hope this help,
Best,
Rémi

**Comment by tobioke** [comment] 2022-12-20 06:59
Hi Rémi,

Everything is now working as before and I can now get those data. You have been very helpful.

Have a happy holiday.

Cheers,

Tobi

**Closed** 2023-01-03 08:55 UTC
Labels: bug
